config/routes.rb
Rails.application.routes.draw do

  root "locations#index"
  resources :locations do 
    resources :reports
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  validates :zipcode, presence: true , length: {in: 5..10 }

  has_many :reports,  :dependent => :delete_all

  def highest_reported
    self.reports.max_by{|report| report.inches}
  end

  def sorted_reports
    self.reports.sort_by {|report| report.inches}.reverse
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :location

  validates :inches, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:destroy, :edit, :show, :update]


  def index 
    locations_with_reports = Location.all.select { |location| location.reports.count > 0}
    location_without_reports = Location.all.select{ |location| location.reports.count == 0}

    # possibly faster 
    locations_hash = {
      with: [],
      without: []
    }

    Location.all.each do |location|
      if location.reports.count > 0
        locations_hash[:with] << location
      else
        locations_hash[:without] << location
      end
    end

    @locations = locations_hash[:with].sort_by{|l| l.highest_reported.inches}.reverse + locations_hash[:without]
    # @locations = locations_with_reports.sort_by{|location| location.highest_reported.inches }.reverse + location_without_reports
  end

  def new 
    @location = Location.new
  end

  def create 
    @location = Location.new(location_params)
    if @location.save
      redirect_to locations_path
      flash[:alert] = "Location correctly added"
    else 
      redirect_to new_location_path, alert: "#{@location.errors.messages[:zipcode][0]}"
    end
  end

  def show

  end

  def edit 

  end

  def update    
    if @location.update(location_params)
      redirect_to locations_path
    else 
      redirect_to edit_location_path(@location), alert: "#{@location.errors.messages[:zipcode][0]}"
    end
  end

  def destroy 
    @location.destroy
  end

  private 

  def set_location 
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:zipcode)
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_location
  def new 
    
    @report = Report.new
  end

  def create
    @report = @location.reports.build(report_params)
    if @report.save 
      redirect_to locations_path
    else 
      render :new
    end
  end 

  private 
  
  def report_params
    params.require(:report).permit(:inches)
  end 

  def set_location 
    @location = Location.find(params[:location_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Snowday</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>  
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <!-- <a class="navbar-brand" href="#">Locations</a> -->
      <img id="logo" src="https://snowday-kga.herokuapp.com/assets/logo-386e5ef6319ed31dd591002c3e0f23914cc37a36357bb5939be74836c3ce9e8d.png" alt="logo" style="width: 60px;">
      <%= link_to "Locations", locations_path, class: "navbar-brand"  %>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        
        <%# <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <!-- <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> -->
        </form> %>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<h1><%= action %> location</h1>
<p> Where should we add to our database? <p>

<%= form_for location do |f| %>
  <div class="form-group">
    <%= f.label :zipcode %>
    <%= f.text_field :zipcode, class: 'form-control'%>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/locations/edit.html.erb
<%= render partial: "locations/form", locals: {location: @location, action: "Edit" }%>

app/views/locations/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">ZIPCODE</th>
      <th scope="col">LARGEST REPORTED SNOWFALL</th>
    </tr>
  </thead>
  <tbody>

    <% @locations.each do |location| %>
      <tr>
        <th scope="row"><%= link_to location.zipcode, location_path(location) %></th>
        <td><%= location.highest_reported ? location.highest_reported.inches.round : "No reports yet"  %></td>
        <td><%= link_to "New Report", new_location_report_path(location), class: "btn btn-primary" %></td>
      </tr>
    <% end %>

    <%# <tr>
      <th scope="row">2</th>
      <td>Jacob</td>
      <td>Thornton</td>
      <td>@fat</td>
    </tr>
    <tr>
      <th scope="row">3</th>
      <td>Larry</td>
      <td>the Bird</td>
      <td>@twitter</td>
    </tr> %>
  </tbody>


</table>

<%= link_to "New Location", new_location_path, class: "btn btn-primary" %>

app/views/locations/new.html.erb
<%= render partial: "locations/form", locals: {location: @location, action: "New" }%>

app/views/locations/show.html.erb
<h3> location: <%= @location.zipcode %></h3>
<%=link_to "edit", edit_location_path, class: "btn btn-info"%>

<br>
<img src="https://maps.googleapis.com/maps/api/staticmap?center=<%=@location.zipcode%>&zoom=13&size=600x200&key=AIzaSyCOJ6MUrEJW9IqYy_UXTM2Np5dMTl4wwwE">

<table class="table">
  <thead>
    <tr>
      <th scope="col">INCHES</th>
      <th scope="col">REPORTED TIME</th>
    </tr>
  </thead>
  <tbody>

    <% @location.sorted_reports.each do |report| %>
      <tr>
        <th scope="row"><%= report.inches.round %></th>
        <td><%= time_ago_in_words(report.created_at) %> ago</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/reports/new.html.erb
<h1>New report</h1>
<p> How much snow fell at <% @location.zipcode%> <p>

<%= form_for @report, url: location_reports_path(@location) do |f| %>
  <div class="form-group">
    <%= f.label :inches %>
    <%= f.text_field :inches, class: 'form-control'%>
  </div>
  <%= f.submit class: "btn btn-primary" %>
<% end %>